### ISSUE TITLE
Two "Users" settings menus

### ISSUE THREAD

**Issue by WebShapedBiz** [esroyo/oc-userprofile-plugin#5]
Hi.
I've added at the top in your `Plugin.php` `use System\Classes\SettingsManager;` and changed `'category'    => SettingsManager::CATEGORY_USERS,` in `public function registerSettings()` so now I don't have two "Users" menu under "Settings".
I think this should be implemented in your next revision since it prevents both cluttering of the "Settings" menu and confusion.

Thank you for your time and effort, it's a wonderful plugin.

Cheers.

**Comment by esroyo** [comment]
Hi WebShapedBiz,
I didn't noticed that they changed the category in the original Rainlab plugin, thanks a lot for taking the time to report this. Should be fixed now.
Best regards.

**Comment by WebShapedBiz** [comment]
You're most welcome.
