### ISSUE TITLE
Tabs in profile - update component

### ISSUE THREAD

**Issue by rusty-ms** [esroyo/oc-userprofile-plugin#6]
The tabs weren't working like in the screenshot. So I wanted to point it out to you:

http://v4-alpha.getbootstrap.com/components/navs/#tabs

```
<ul id="user-profile-tabs" class="nav nav-tabs" data-tabs="user-profile-tabs">
        <li class="active nav-item"><a href="#{{ str_slug(account_tab) }}" data-toggle="tab" class="nav-link active">{{ account_tab }}</a></li>

        {% for tab, fields in user_profile_fields %}
            <li class="nav-item"><a href="#{{ str_slug(tab) }}" data-toggle="tab" class="nav-link">{{ tab }}</a></li>
        {% endfor %}

    </ul>
```

I added `class="nav-link"` and `class="nav-link action"` to the href's and `class="nav-item"` to the li's.

**Comment by esroyo** [comment]
@rustytheitgod I couldn't reproduce this. I guess it depends on your theme using Bootstrap v3 or v4. Anyway I've added the v4 classes, as it doesn't affect v3 users. Thanks for taking the time to report. Kind regards.
